#pragma checksum "..\..\PatherExplorerGui.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "09601EE846F226219EFDD2A8989F1F23FCDBCECE386BABF4853520998D005120"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PatherExplorer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PatherExplorer {
    
    
    /// <summary>
    /// PatherExplorerGui
    /// </summary>
    public partial class PatherExplorerGui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MainGrid;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Map_Border;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Map_Picture;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Obstacles_Border;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Obstacles_Picture;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Raycast_Border;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Raycast_Picture;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FindPath_Result_Border;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image FindPath_Result_Picture;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Next_Selected_Walk_Position_Border;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Next_Selected_Walk_Position_Picture;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Tgts_Border;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Tgts_Picture;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border My_Pos_Border;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image My_Pos_Picture;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup PopupWindow;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PopupWindow_txt;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox Graphic_Quality_ComboBox;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider Fps_Slider;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReloadExilePatherButton;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LockCameraToPlayer_cb;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ShowFlyMap_cb;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox BlockLockedDoors_ComboBox;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox BlockTrialOfAscendancy_ComboBox;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox BlockLockedTempleDoors_ComboBox;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlayerLocationText;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Pathfind_Origin_X_txt;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Pathfind_Origin_Y_txt;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Pathfind_Origin_btn;
        
        #line default
        #line hidden
        
        
        #line 233 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Pathfind_Destinatio_X_txt;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Pathfind_Destinatio_Y_txt;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Pathfind_Destinatio_btn;
        
        #line default
        #line hidden
        
        
        #line 250 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider Nodes_Dist_Slider;
        
        #line default
        #line hidden
        
        
        #line 275 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CreatePath_btn;
        
        #line default
        #line hidden
        
        
        #line 287 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Track_Tgts_under_Player_CheckBox;
        
        #line default
        #line hidden
        
        
        #line 298 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider Tgts_Range_Slider;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Tgts_TextBlock;
        
        #line default
        #line hidden
        
        
        #line 342 "..\..\PatherExplorerGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Tdts_TextBlock;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PatherExplorer;component/patherexplorergui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\PatherExplorerGui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MainGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.Map_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.Map_Picture = ((System.Windows.Controls.Image)(target));
            return;
            case 4:
            this.Obstacles_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.Obstacles_Picture = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.Raycast_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.Raycast_Picture = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.FindPath_Result_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.FindPath_Result_Picture = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.Next_Selected_Walk_Position_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.Next_Selected_Walk_Position_Picture = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.Tgts_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.Tgts_Picture = ((System.Windows.Controls.Image)(target));
            return;
            case 14:
            this.My_Pos_Border = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.My_Pos_Picture = ((System.Windows.Controls.Image)(target));
            
            #line 90 "..\..\PatherExplorerGui.xaml"
            this.My_Pos_Picture.MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.MapPicture_OnMouseWheel);
            
            #line default
            #line hidden
            
            #line 91 "..\..\PatherExplorerGui.xaml"
            this.My_Pos_Picture.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MapPicture_OnMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 92 "..\..\PatherExplorerGui.xaml"
            this.My_Pos_Picture.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.MapPicture_OnMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 93 "..\..\PatherExplorerGui.xaml"
            this.My_Pos_Picture.MouseMove += new System.Windows.Input.MouseEventHandler(this.MapPicture_OnMouseMove);
            
            #line default
            #line hidden
            
            #line 94 "..\..\PatherExplorerGui.xaml"
            this.My_Pos_Picture.MouseRightButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.My_Pos_Picture_OnMouseRightButtonDown);
            
            #line default
            #line hidden
            return;
            case 16:
            this.PopupWindow = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 110 "..\..\PatherExplorerGui.xaml"
            this.PopupWindow.MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.MapPicture_OnMouseWheel);
            
            #line default
            #line hidden
            
            #line 111 "..\..\PatherExplorerGui.xaml"
            this.PopupWindow.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MapPicture_OnMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 112 "..\..\PatherExplorerGui.xaml"
            this.PopupWindow.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.MapPicture_OnMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 113 "..\..\PatherExplorerGui.xaml"
            this.PopupWindow.MouseMove += new System.Windows.Input.MouseEventHandler(this.MapPicture_OnMouseMove);
            
            #line default
            #line hidden
            
            #line 114 "..\..\PatherExplorerGui.xaml"
            this.PopupWindow.MouseRightButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.My_Pos_Picture_OnMouseRightButtonDown);
            
            #line default
            #line hidden
            return;
            case 17:
            this.PopupWindow_txt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.Graphic_Quality_ComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 130 "..\..\PatherExplorerGui.xaml"
            this.Graphic_Quality_ComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Graphic_Quality_ComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.Fps_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 146 "..\..\PatherExplorerGui.xaml"
            this.Fps_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.Fps_Slider_OnValueChanged);
            
            #line default
            #line hidden
            return;
            case 20:
            this.ReloadExilePatherButton = ((System.Windows.Controls.Button)(target));
            
            #line 154 "..\..\PatherExplorerGui.xaml"
            this.ReloadExilePatherButton.Click += new System.Windows.RoutedEventHandler(this.ReloadExilePatherButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 21:
            this.LockCameraToPlayer_cb = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 22:
            this.ShowFlyMap_cb = ((System.Windows.Controls.CheckBox)(target));
            
            #line 158 "..\..\PatherExplorerGui.xaml"
            this.ShowFlyMap_cb.Checked += new System.Windows.RoutedEventHandler(this.ShowFlyMap_cb_CheckBoxChanged);
            
            #line default
            #line hidden
            
            #line 158 "..\..\PatherExplorerGui.xaml"
            this.ShowFlyMap_cb.Unchecked += new System.Windows.RoutedEventHandler(this.ShowFlyMap_cb_CheckBoxChanged);
            
            #line default
            #line hidden
            return;
            case 23:
            this.BlockLockedDoors_ComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 188 "..\..\PatherExplorerGui.xaml"
            this.BlockLockedDoors_ComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.BlockLockedDoors_ComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 24:
            this.BlockTrialOfAscendancy_ComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 192 "..\..\PatherExplorerGui.xaml"
            this.BlockTrialOfAscendancy_ComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.BlockTrialOfAscendancy_ComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 25:
            this.BlockLockedTempleDoors_ComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 196 "..\..\PatherExplorerGui.xaml"
            this.BlockLockedTempleDoors_ComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.BlockLockedTempleDoors_ComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 26:
            this.PlayerLocationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.Pathfind_Origin_X_txt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.Pathfind_Origin_Y_txt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.Pathfind_Origin_btn = ((System.Windows.Controls.Button)(target));
            
            #line 228 "..\..\PatherExplorerGui.xaml"
            this.Pathfind_Origin_btn.Click += new System.Windows.RoutedEventHandler(this.Pathfind_Origin_btn_OnClick);
            
            #line default
            #line hidden
            return;
            case 30:
            this.Pathfind_Destinatio_X_txt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.Pathfind_Destinatio_Y_txt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            this.Pathfind_Destinatio_btn = ((System.Windows.Controls.Button)(target));
            
            #line 237 "..\..\PatherExplorerGui.xaml"
            this.Pathfind_Destinatio_btn.Click += new System.Windows.RoutedEventHandler(this.Pathfind_Destinatio_btn_OnClick);
            
            #line default
            #line hidden
            return;
            case 33:
            this.Nodes_Dist_Slider = ((System.Windows.Controls.Slider)(target));
            return;
            case 34:
            this.CreatePath_btn = ((System.Windows.Controls.Button)(target));
            
            #line 275 "..\..\PatherExplorerGui.xaml"
            this.CreatePath_btn.Click += new System.Windows.RoutedEventHandler(this.CreatePath_btn_OnClick);
            
            #line default
            #line hidden
            return;
            case 35:
            this.Track_Tgts_under_Player_CheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 36:
            this.Tgts_Range_Slider = ((System.Windows.Controls.Slider)(target));
            return;
            case 37:
            this.Tgts_TextBlock = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.Tdts_TextBlock = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

